// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";

import { AITO_SAYED$Type } from "./AITO_SAYED";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["AITO_SAYED"]: AITO_SAYED$Type;
    ["contracts/AITO_SAYED.sol:AITO_SAYED"]: AITO_SAYED$Type;
  }
}
